inherit_gem:
  dxw-utils:
    - dxw-rubocop.yml

Metrics/AbcSize:
  Max: 25
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/routes.rb'
    - 'config/environments/*'
    - 'config/initializers/devise.rb'

Metrics/MethodLength:
  Max: 25

Naming/AccessorMethodName:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false
