version: '3.1'
services:
  test: &test
    build:
      context: .
      args:
        RAILS_ENV: "test"
    environment:
      RAILS_ENV: "test"
      DATABASE_URL: "postgres://postgres@db-test:5432/request-a-repair-purple?template=template0&pool=5&encoding=unicode"
    container_name: request-a-repair-purple_test_web_1
    env_file:
      - docker-compose.env
    volumes:
      - .:/srv/request-a-repair-purple:cached
      - node_modules:/srv/request-a-repair-purple/node_modules:cached
    depends_on:
      - db-test
    command: ["bundle", "exec", "./bin/dsetup && spring server"]
    restart: on-failure
    networks:
      - tests

  db-test:
    image: postgres
    container_name: request-a-repair-purple_test_db_1
    volumes:
      - pg_test_data:/var/lib/postgresql/data/:cached
    networks:
      - tests
    restart: on-failure

networks:
  tests:

volumes:
  pg_test_data: {}
  node_modules:
