version: '3.1'
services:
  web:
    build:
      context: .
      args:
        RAILS_ENV: "development"
    ports: ["3000:3000"]
    container_name: request-a-repair-purple_dev_web_1
    environment:
      RAILS_ENV: "development"
    env_file:
      - docker-compose.env
    depends_on:
      - db
    tty: true
    stdin_open: true
    restart: on-failure
    volumes:
      - .:/srv/request-a-repair-purple:cached
      - node_modules:/srv/request-a-repair-purple/node_modules
    command: bash -c "rm -f tmp/pids/server.pid && rails s"

  db:
    image: postgres
    container_name: request-a-repair-purple_dev_db_1
    volumes:
      - pg_data:/var/lib/postgresql/data/:cached
    restart: on-failure

volumes:
  pg_data: {}
  node_modules:
